eureka.client.service-url.defaultZone: http://localhost:5858/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: product_service
          uri: http://localhost:5861/
          predicates:
            - Path=/product/**

        - id: user-service
          uri: http://localhost:5862/
          predicates:
            - Path=/users/**, /auth/**


        - id: order_service
          uri: http://localhost:5863/
          predicates:
            - Path=/order/**, /cart/**
