eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:5858/eureka"

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/order-db"
    driver-class-name: "org.postgresql.Driver"
    username: "postgres"
    password: "password"

  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
      javax:
        persistence:
          validation:
            mode: "none"

    hibernate:
      ddl-auto: "update"